version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
    volumes:
      - ./src/database/progress.db:/usr/src/app/dist/database/progress.db
    restart: unless-stopped
